[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gptune"
version = "5.0.0"
description = "GPTune: autotuning framework"
readme = "README.md"


# ðŸ‘‡ Minimum Python version
requires-python = ">=3.8"

